src/home/urls.py
from django.urls import path
from . import views


app_name = 'home'


urlpatterns = [
    path('', views.home , name='home'),
]

src/project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('property/', include('property.urls' , namespace='property') ),
    path('agents/', include('agents.urls' , namespace='agents') ),
    path('about/', include('about.urls' , namespace='about') ),
    path('contact/', include('contact.urls' , namespace='contact') ),
    path('', include('home.urls' , namespace='home') )
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




admin.site.site_header = "AGENCY RESERVATION ADMINISTRATION"
admin.site.site_title = "AGENCY RESERVATION ADMINISTRATION"
admin.site.site_index_title = "Welcome To Agency Reservation Administration"

src/property/urls.py
from django.urls import path
from . import views


app_name = 'property'

urlpatterns = [
    path('', views.property_list , name='property_list'),
    path('<int:id>', views.property_detail , name='property_detail'),
]

src/property/models.py
from django.db import models

# Create your models here.

property_type = (
    ('Sale', "sale"),
    ('Rent', "rent")
)

class Property(models.Model):
    name = models.CharField(max_length=50)
    adress = models.CharField( max_length=80)
    type = models.CharField(choices=property_type, max_length=50)
    category = models.ForeignKey("Category",null=True , on_delete=models.SET_NULL)
    price = models.PositiveIntegerField()
    area = models.DecimalField( max_digits=5, decimal_places=2)
    rooms_number = models.PositiveIntegerField()
    beds_number = models.PositiveIntegerField()
    baths_number = models.PositiveIntegerField()
    garages_number = models.PositiveIntegerField()
    image = models.ImageField(upload_to='property/', height_field=None, width_field=None, max_length=None)


    class Meta:
        verbose_name = ("Property")
        verbose_name_plural = ("properties")

    def __str__(self):
        return self.name





class Category(models.Model):
    category_name = models.CharField(max_length=50)
    category_image = models.ImageField(upload_to='category/', height_field=None, width_field=None, max_length=None)

    class Meta:
        verbose_name = ("category")
        verbose_name_plural = ("categories")

    def __str__(self):
        return self.category_name




class Reserve(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    notes = models.TextField()

    class Meta:
        verbose_name = ("Reserve")
        verbose_name_plural = ("Reservations")

    def __str__(self):
        return self.name

src/property/forms.py
from django import forms 
from .models import Reserve


class ReserveForm(forms.ModelForm):
    
    class Meta:
        model = Reserve
        fields = "__all__"

src/property/views.py
from django.shortcuts import render

# Create your views here.
from .models import Property , Category
from .forms import ReserveForm
from django.db.models import Q
def property_list(request):
    property_list = Property.objects.all()
    template = 'property/list.html'


    adress_query = request.GET.get('q')
    property_type = request.GET.getlist('property_type' , None)
    if adress_query and property_type :
        property_list = property_list.filter(
            Q(adress__icontains = adress_query) &
            Q(type__icontains = property_type[0])
        ).distinct()


    context = {
        'property_list' : property_list
    }

    return render(request, template , context)




def property_detail(request, id):
    property_detail = Property.objects.get(id=id)
    template = 'property/detail.html'


    if request.method == 'POST':
        reserve_form = ReserveForm(request.POST)
        if reserve_form.is_valid():
            reserve_form.save()


    else:
        reserve_form = ReserveForm()


    context = {
        'property_detail' : property_detail ,
        'reserve_form' : reserve_form
    }

    return render(request, template, context)

src/property/templates/property/detail.html
 {% extends 'base.html' %}
 {% load bootstrap4 %}
 {% block body %}
  <!-- END: header -->
  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="#">Home</a><span><a href="{% url 'property:property_list' %}"> Properties </a></span>
              </div>
              <h1>{{property_detail}}</h1>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url(img/slider_1.jpg);"></li>
      <li style="background-image: url(img/slider_4.jpg);"></li>
      <li style="background-image: url(img/slider_2.jpg);"></li>
    </ul>
  </section>
  <!-- END: slider  -->

  <section class="probootstrap-section">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p><img src="{{property_detail.image.url}}" class="img-responsive" ></p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <h2>Description</h2>
          <p><strong>{{property_detail.category}}</strong></p>
          <p>For {{property_detail.type}}</p>
          <p>{{property_detail.adress}}</p>
          <p>{{property_detail.price}} $</p>
          <p>Area: {{property_detail.area}}m²</p>
          <p>Rooms: {{property_detail.rooms_number}}</p>
          <p>Beds: {{property_detail.beds_number}}</p>
          <p>Baths: {{property_detail.baths_number}}</p>
          <p>Garages: {{property_detail.garages_number}}</p>
        </div>
      </div>
    </div>
  </section>

    <section class="probootstrap-section">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>Reserve This Property</h2>
            <form action="" method="POST">
              {% csrf_token %}
              {% bootstrap_form reserve_form %}
              {% buttons %}
                  <button type="submit" class="btn btn-primary">Reserve</button>
              {% endbuttons %}
            </form>
        </div>
      </div>
    </div>
  </section>



  

  {% endblock body %}

src/property/templates/property/list.html
 {% extends 'base.html' %}

 {% block body %}

  <!-- END: header -->
  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="#">Home</a><span>Properties</span>
              </div>
              <h1>Properties</h1>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url(img/slider_1.jpg);"></li>
      <li style="background-image: url(img/slider_4.jpg);"></li>
      <li style="background-image: url(img/slider_2.jpg);"></li>
    </ul>
  </section>
  <!-- END: slider  -->

  <section class="probootstrap-section probootstrap-section-lighter">
    <div class="container">
      <div class="row">

        {% if property_list %}

          {% for property in property_list %}
            <div class="col-md-4 col-sm-6">
              <div class="probootstrap-card probootstrap-listing">
                <div class="probootstrap-card-media">
                  <img src="{{property.image.url}}" class="img-responsive" alt="">
                  <a href="#" class="probootstrap-love"><i class="icon-heart"></i></a>
                </div>
                <div class="probootstrap-card-text">
                  <h2 class="probootstrap-card-heading"><a href="{% url 'property:property_detail' property.id %}">{{property.name}}</a></h2>
                  <div class="probootstrap-listing-location">
                    <i class="icon-location2"></i> <span>{{property.adress}}</span>
                  </div>
                  <div class="probootstrap-listing-category for-sale"><span>for {{property.type}}</span></div>
                  <div class="probootstrap-listing-price"><strong>$ {{property.price}}</strong> / month</div>
                </div>
                <div class="probootstrap-card-extra">
                  <ul>
                    <li>
                      Area
                      <span>{{property.area}} m2</span>
                    </li>
                    <li>
                      Rooms
                      <span>{{property.rooms_number}}</span>
                    </li>
                    <li>
                      Beds
                      <span>{{property.beds_number}}</span>
                    </li>
                    <li>
                      Baths
                      <span>{{property.baths_number}}</span>
                    </li>
                  </ul>
                </div>
              </div>
              <!-- END listing -->
            </div>
          {% endfor %}

        {% else %}

            <div class="col-md-10 col-sm-10">
              <h2>No Property with this Adress or Type</h2>
            </div>

        {% endif %}
      </div>
    </div>
  </section>

  

   {% endblock body %}